# Generated by Django 2.2.2 on 2019-06-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_appointments_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
