# Generated by Django 2.2.2 on 2019-06-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20190625_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
